"""initial_schema

Revision ID: b06bbfea96cd
Revises: 
Create Date: 2026-05-13 06:51:44.465557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06bbfea96cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.String(length=10), nullable=False),
    sa.Column('account_value', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('daily_pl', sa.Float(), nullable=False),
    sa.Column('realized_pl', sa.Float(), nullable=False),
    sa.Column('unrealized_pl', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('signals_generated', sa.Integer(), nullable=False),
    sa.Column('signals_traded', sa.Integer(), nullable=False),
    sa.Column('signals_alerted', sa.Integer(), nullable=False),
    sa.Column('signals_ignored', sa.Integer(), nullable=False),
    sa.Column('best_trade_ticker', sa.String(length=16), nullable=True),
    sa.Column('best_trade_pl', sa.Float(), nullable=True),
    sa.Column('worst_trade_ticker', sa.String(length=16), nullable=True),
    sa.Column('worst_trade_pl', sa.Float(), nullable=True),
    sa.Column('risk_events_count', sa.Integer(), nullable=False),
    sa.Column('paper_mode', sa.Boolean(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('sent_telegram', sa.Boolean(), nullable=False),
    sa.Column('sent_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_report_report_date'), 'daily_report', ['report_date'], unique=True)
    op.create_table('portfolio_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_value', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('unrealized_pl', sa.Float(), nullable=False),
    sa.Column('realized_pl_today', sa.Float(), nullable=False),
    sa.Column('daily_pl', sa.Float(), nullable=False),
    sa.Column('trades_today', sa.Integer(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('paper_mode', sa.Boolean(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('unrealized_pl', sa.Float(), nullable=False),
    sa.Column('unrealized_pl_pct', sa.Float(), nullable=False),
    sa.Column('paper_mode', sa.Boolean(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_snapshot_ticker'), 'position_snapshot', ['ticker'], unique=False)
    op.create_table('risk_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('triggered_value', sa.Float(), nullable=True),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ticker_detected', sa.String(length=16), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_item_dedup_hash'), 'source_item', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_source_item_ticker_detected'), 'source_item', ['ticker_detected'], unique=False)
    op.create_table('system_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_log_ticker'), 'system_log', ['ticker'], unique=False)
    op.create_table('user_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_config_key'), 'user_config', ['key'], unique=True)
    op.create_table('watchlist_ticker',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_position_usd', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_ticker_ticker'), 'watchlist_ticker', ['ticker'], unique=True)
    op.create_table('verified_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('sentiment', sa.String(length=32), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('corroboration_score', sa.Float(), nullable=False),
    sa.Column('duplicate_story_score', sa.Float(), nullable=False),
    sa.Column('market_reaction_score', sa.Float(), nullable=False),
    sa.Column('final_confidence_score', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=32), nullable=False),
    sa.Column('corroborating_source_ids', sa.JSON(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verified_event_ticker'), 'verified_event', ['ticker'], unique=False)
    op.create_table('ai_signal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('verified_event_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('event_summary', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('sentiment', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_time_horizon', sa.String(length=32), nullable=False),
    sa.Column('expected_price_impact', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('trade_decision', sa.String(length=32), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('sources_used', sa.JSON(), nullable=True),
    sa.Column('raw_ai_response', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['verified_event_id'], ['verified_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_signal_ticker'), 'ai_signal', ['ticker'], unique=False)
    op.create_table('trade_decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_signal_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.Column('risk_check_passed', sa.Boolean(), nullable=False),
    sa.Column('risk_check_notes', sa.Text(), nullable=True),
    sa.Column('paper_mode', sa.Boolean(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('ignored_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_signal_id'], ['ai_signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_decision_ticker'), 'trade_decision', ['ticker'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_decision_id', sa.String(length=36), nullable=True),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paper_mode', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trade_decision_id'], ['trade_decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_broker_order_id'), 'order', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_order_ticker'), 'order', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_ticker'), table_name='order')
    op.drop_index(op.f('ix_order_broker_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_trade_decision_ticker'), table_name='trade_decision')
    op.drop_table('trade_decision')
    op.drop_index(op.f('ix_ai_signal_ticker'), table_name='ai_signal')
    op.drop_table('ai_signal')
    op.drop_index(op.f('ix_verified_event_ticker'), table_name='verified_event')
    op.drop_table('verified_event')
    op.drop_index(op.f('ix_watchlist_ticker_ticker'), table_name='watchlist_ticker')
    op.drop_table('watchlist_ticker')
    op.drop_index(op.f('ix_user_config_key'), table_name='user_config')
    op.drop_table('user_config')
    op.drop_index(op.f('ix_system_log_ticker'), table_name='system_log')
    op.drop_table('system_log')
    op.drop_index(op.f('ix_source_item_ticker_detected'), table_name='source_item')
    op.drop_index(op.f('ix_source_item_dedup_hash'), table_name='source_item')
    op.drop_table('source_item')
    op.drop_table('risk_event')
    op.drop_index(op.f('ix_position_snapshot_ticker'), table_name='position_snapshot')
    op.drop_table('position_snapshot')
    op.drop_table('portfolio_snapshot')
    op.drop_index(op.f('ix_daily_report_report_date'), table_name='daily_report')
    op.drop_table('daily_report')
    # ### end Alembic commands ###
